import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Desktop from '../components/View/Desktop';
import Mobile from '../components/View/Mobile';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi QR APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Desktop />
        <Mobile />
      </main>

    </div>
  )
}
